---
# SPDX-License-Identifier: GPL-3.0-or-later
# (c) 2020-2024 Peter Mosmans [Go Forward]
#
# Executes njsscan over source code.
#
# Variables:
# NJSSCAN_VERSION    Specifies which version of opensecurity/njsscan is being used

njsscan:
  extends: .sast
  image:
    name: opensecurity/njsscan:${NJSSCAN_VERSION}
    entrypoint: [""]
  before_script:
    - mkdir -p reports &>/dev/null || true
  script:
    - >
      njsscan --output reports/njsscan-report.txt . ;
      njsscan --exit-warning --sonarqube --output reports/njsscan-report.json .
  # Always show report
  after_script:
    - cat reports/njsscan-report.txt
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - reports/njsscan-report.*
  # Only flag the job as failed, not the whole pipeline
  allow_failure: true
